const API_KEY = process.env.USER_GEMINI_API_KEY || process.env.GEMINI_API_KEY || "";
const BASE_URL = process.env.USER_GEMINI_BASE_URL || "https://generativelanguage.googleapis.com/v1beta";
const MODEL = process.env.USER_GEMINI_MODEL || "gemini-3.6-flash";

export function isLive() {
  return !!API_KEY;
}

export function currentModel() {
  return isLive() ? MODEL : "localboost-sim-v1";
}

async function callGemini({ system, prompt, json = false }) {
  const body = {
    contents: [
      {
        role: "user",
        parts: [{ text: system ? `${system}\n\n${prompt}` : prompt }],
      },
    ],
    generationConfig: {
      temperature: 0.7,
      ...(json ? { responseMimeType: "application/json" } : {}),
    },
  };
  const res = await fetch(
    `${BASE_URL}/models/${MODEL}:generateContent`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": API_KEY,
      },
      body: JSON.stringify(body),
    },
  );
  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Gemini API error ${res.status}: ${errText.slice(0, 200)}`);
  }
  const data = await res.json();
  const text =
    data?.candidates?.[0]?.content?.parts?.map((p) => p.text || "").join("") || "";
  return text.trim();
}

export async function generate({ system = "", prompt = "", context = {}, json = false, forceSim = false }) {
  if (!isLive() || forceSim) {
    return { text: simulate(context), simulated: true, model: currentModel() };
  }
  try {
    const text = await callGemini({ system, prompt, json });
    return { text, simulated: false, model: currentModel() };
  } catch (err) {
    console.warn("[llm] fallback to simulation:", err.message);
    return { text: simulate(context), simulated: true, model: currentModel() };
  }
}

const CONTENT_SNIPPETS = [
  "Our weekend special just landed — and it is worth the trip. Swing by today and see why the neighborhood keeps coming back.",
  "New week, new reasons to stop in. Fresh batch out now, while supplies last.",
  "We are donating 5% of every sale this month to a local cause. Come do good and feel good.",
  "Small businesses make neighborhoods great. Support local, shop with us this week.",
  "POV: your best coffee of the week is waiting. Open until 7pm tonight.",
  "Limited drop: our signature item is back by popular demand. Get yours before they are gone.",
  "Big news for regulars — loyalty rewards just got better. Ask us in store today.",
  "Five-star service is our standard, not our goal. Come see what local means to us.",
];

const SOCIAL_SNIPPETS = [
  "Here is a look behind the counter at everything we make fresh daily.",
  "The team behind the counter you love. Say hi next time you are in!",
  "Sunday reset: what your week looks like when local businesses power it.",
  "A little recap of our busiest week yet — thank YOU, neighborhood.",
];

const SUPPORT_REPLIES = [
  "Thanks for reaching out! We will have a full answer for you shortly. Meanwhile, could you confirm your order number so we can pull up the details?",
  "Great question — happy to help! We will check our records and get back to you within the hour with everything you need.",
  "Appreciate your patience. We have escalated this to our team and you will hear from us very soon with a resolution.",
  "We are on it! A team member will follow up with specifics shortly. Thank you for being a valued customer.",
];

const REPORT_TEMPLATE = (biz) => `# ${biz} — Weekly Performance Report

## Highlights
- Engagement up **12%** week-over-week across all channels.
- Your best-performing post was published by the Content Agent; it drove **38** new link clicks.
- Support Agent resolved **100%** of inbound questions within 15 minutes.

## Recommendations (generated by the Analytics Agent)
1. Post morning content between **8–10am** — engagement peaks there.
2. Run a weekend promotion to convert new followers into store visits.
3. Reply to the 2 unanswered reviews collected this week.

## Goal Check
We are pacing ahead of your monthly goal. Revenue attributable to agent-run campaigns is trending toward **$1,480** this month.`;

const PLAN_TEMPLATE = (biz) => `# ${biz} — 30-Day Growth Plan (drafted by SalesOnboardingAgent)

## Week 1: Foundation
- Complete Google Business profile and local listings cleanup.
- Publish 4 content posts; enable the Support Agent for customer chat.

## Week 2: Momentum
- Launch a referral offer ("bring a friend, both save").
- Social Agent begins posting 3x/week; Analytics Agent sets baseline KPIs.

## Week 3: Optimize
- Double down on best-performing content formats.
- Billing Agent issues first recurring invoice and tracks payment.

## Week 4: Scale
- Review the Analytics Agent report; approve next month's plan.
- Target: +20% in-store visits and 100+ new social followers.`;

function pick(arr, seed) {
  let i = 0;
  for (const c of String(seed)) i = (i * 31 + c.charCodeAt(0)) % arr.length;
  return arr[Math.abs(i) % arr.length];
}

function hash(str) {
  let h = 0;
  for (const c of String(str)) h = (h * 31 + c.charCodeAt(0)) | 0;
  return String(h);
}

export function simulate(context = {}) {
  const kind = context.kind || "generic";
  const seed = hash(JSON.stringify(context));
  const biz = context.businessName || "your business";
  const platform = context.platform || "Facebook";
  const replyText = pick(SUPPORT_REPLIES, seed);

  switch (kind) {
    case "content":
      return `[${platform}] ${pick(CONTENT_SNIPPETS, seed)}`.replace(
        "Fresh batch out now",
        `Fresh batch out now at ${biz}`,
      );
    case "social":
      return pick(SOCIAL_SNIPPETS, seed);
    case "support":
      return replyText;
    case "report":
      return REPORT_TEMPLATE(biz);
    case "plan":
      return PLAN_TEMPLATE(biz);
    case "billing":
      return JSON.stringify({
        amount: context.amount || 499,
        due_date: context.dueDate || "2026-09-01",
        memo: `Monthly AI Agency subscription for ${biz}`,
      });
    case "analytics":
      return JSON.stringify({
        recommendation: `Increase posting frequency on ${platform} to 4x/week.`,
        projected_revenue: 1480,
      });
    case "onboard":
      return JSON.stringify({
        tagline: `${biz} — where the neighborhood feels like home.`,
        recommended_plan: "Essentials",
      });
    default:
      return `Understood. I will handle this for ${biz} now.`;
  }
}
